### ISSUE TITLE
filter throw checked excaption, but got UndeclaredThrowableException

### ISSUE THREAD

**Issue by wangyongxu** [wangyongxu/wu#1]
Filter: 
```java
    public static class AuthFilter implements WuFilter {
        private static final Logger logger = LoggerFactory.getLogger(AuthFilter.class);

        @Override
        public boolean before(Invocation invocation, ApiResult apiResult) throws Exception {
            logger.info("invocation: {}", invocation);
//            boolean b = RandomUtils.nextBoolean();
//            if (b) {
//                logger.info("success! ");
//                return true;
//            }
            throw new IllegalAccessException("user auth error");
        }

        @Override
        public void after(Invocation invocation, ApiResult apiResult) throws Exception {
            logger.info("after,result: {} ", apiResult);
        }

        @Override
        public void complete(Invocation invocation, ApiResult apiResult, Exception ex) {
            logger.info("complete, result: {}", apiResult);
        }
    }
```

but got this: 
```log

org.opentest4j.AssertionFailedError: user auth error ==> Unexpected exception type thrown ==> expected: <java.lang.IllegalAccessException> but was: <java.lang.reflect.UndeclaredThrowableException>

	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:65)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:41)
	at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3024)
	at com.github.wu.spring.RpcWuFilterTest.testWuService(RpcWuFilterTest.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy55.echo(Unknown Source)
	at com.github.wu.spring.RpcWuFilterTest.lambda$testWuService$0(RpcWuFilterTest.java:37)
	at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:55)
	... 70 more
Caused by: java.lang.IllegalAccessException: user auth error
	at com.github.wu.spring.RpcWuFilterTest$AuthFilter.before(RpcWuFilterTest.java:55)
	at com.github.wu.core.rpc.filter.FilterChain.applyBefore(FilterChain.java:37)
	at com.github.wu.core.rpc.proxy.InvokerInvocationHandler.call(InvokerInvocationHandler.java:57)
	at com.github.wu.core.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:49)
	... 73 more


```

**Comment by wangyongxu** [comment]
由于目前的过滤器实现是依靠jdk的动态代理，但是filter中可以抛出受检异常，动态代理生成的类，在调用过程中抛出了接口为声明的异常，所以抛出了`UndeclaredThrowableException`异常，该异常的[doc](https://docs.oracle.com/javase/8/docs/api/java/lang/reflect/UndeclaredThrowableException.html)说明很明确。

考虑以下几点:
1. 过滤器的实现是可能会抛出受检异常的，所以filter的有exception的签名应该是ok的;
2. 目前的过滤器的时机是在进入server端后，反射调用服务端调用的时执行的，时机很靠后，客户端可以插入的业务逻辑的时机不够多。如如果客户端想支持本地的参数验证，目前的filter设计无法实现。

由此可以看出，过滤器不适合在这个阶段执行，需要调整filter的执行时机，执行时间点的选择有以下2个:
1. 集群选择前;
2. 集群选择节点后，节点调用前;

集群选择前是最为靠前的时间点，此时可以获得集群选择情况，暴露的能力是最大的，但是如果在ha阶段进行了转移或者广播，此时就一次调用；

后者是选中节点后调用前，特点:
1. 节点已经选择，不好再进行转移；
2. 如果发送了转移，filter会进行多次调用;

filter的时机决定了不同的理念，可以参考下其他rpc框架，结合一些场景决定调用时机。

**Comment by wangyongxu** [comment]
这个问题应该分为3个小问题:
1. 能不能改变被代理对象的方法签名(指抛出源方法签名中不存在的受检异常);
2. filter存在于应用代理模式的地方;
3. 过滤器调用时机;

第一个问题， 在示例中，接口方法不存在`IllegalAccessException`，但是**在过滤器中抛出了该异常，相当于修改了被代理对象的方法签名，这是不应该的**。站在使用者的角度看，由于在filter中抛出了方法中不存在的异常，对于使用者也是不好的使用体验，所以Filter不应该抛出受检异常，应该抛出非受检异常;

第二个问题，对于一些场景，在进行rpc调用之前，可以进行本地的校验过滤掉无效请求，如参数校验，不必都放在服务端校验，客户端也可以先进行校验，类似的还有，权限、限流、降级、缓存等等；所以**过滤器需要分为客户端和服务端**

第三个问题，对于使用者来说，最关注的是此次经过filter的调用是否成功，重点是该次调用，集群节点的选择并不是当前关注的事情，并且调用节点的选择目前也提供了扩展点，应该在`ClusterInvoker`的时候关注节点的选择，所以filter发生在**2. 集群选择节点后，节点调用前**
