### ISSUE TITLE
连续调用多个方法时，抛出UnsupportedProtocolException: magic: -21267

### ISSUE THREAD

**Issue by Kunple-w** [wangyongxu/wu#5]
**bug描述**
连续调用多个方法时，抛出`Caused by: com.github.wu.common.exception.UnsupportedProtocolException: magic: -21267`

**bug复现**
bug复现步骤:
1. 运行单测`com.github.wu.spring.RpcAnnotationTest#testWuServiceEcho`

**期望的结果**
单测正常

**截图**

![image](https://user-images.githubusercontent.com/15710694/118073766-149f5f80-b3df-11eb-85d0-c1d4aa906856.png)

**使用环境:**
 - OS: [win 10]
 - jdk11

**额外信息**
堆栈信息
```log
2021-05-13 11:23:01.583  INFO 19604 --- [ntLoopGroup-5-1] c.g.wu.core.transport.ClientHandler      : write: Request(header=com.github.wu.core.transport.SengProtocolHeader@39a9fc56, body=Invocation(serviceName=com.github.wu.spring.biz.EmailService, methodName=echo, args=[wu, hello world]))
2021-05-13 11:23:01.584  INFO 19604 --- [ntLoopGroup-5-1] c.g.w.core.transport.SengMessageEncoder  : encode: Request(header=com.github.wu.core.transport.SengProtocolHeader@39a9fc56, body=Invocation(serviceName=com.github.wu.spring.biz.EmailService, methodName=echo, args=[wu, hello world]))
2021-05-13 11:23:01.584 DEBUG 19604 --- [ntLoopGroup-5-1] io.netty.handler.logging.LoggingHandler  : [id: 0xae42d441, L:/172.31.208.1:58682 - R:/172.31.208.1:11996] WRITE: 153B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| fd ac 01 01 00 00 00 00 00 00 00 00 02 00 00 00 |................|
|00000010| 88 ac ed 00 05 77 50 00 25 63 6f 6d 2e 67 69 74 |.....wP.%com.git|
|00000020| 68 75 62 2e 77 75 2e 73 70 72 69 6e 67 2e 62 69 |hub.wu.spring.bi|
|00000030| 7a 2e 45 6d 61 69 6c 53 65 72 76 69 63 65 00 04 |z.EmailService..|
|00000040| 65 63 68 6f 00 21 6a 61 76 61 2e 6c 61 6e 67 2e |echo.!java.lang.|
|00000050| 53 74 72 69 6e 67 2c 6a 61 76 61 2e 6c 61 6e 67 |String,java.lang|
|00000060| 2e 53 74 72 69 6e 67 75 72 00 02 5b 42 ac f3 17 |.Stringur..[B...|
|00000070| f8 06 08 54 e0 02 00 00 78 70 00 00 00 04 22 77 |...T....xp...."w|
|00000080| 75 22 75 71 00 7e 00 00 00 00 00 0d 22 68 65 6c |u"uq.~......"hel|
|00000090| 6c 6f 20 77 6f 72 6c 64 22                      |lo world"       |
+--------+-------------------------------------------------+----------------+
2021-05-13 11:23:01.584 DEBUG 19604 --- [ntLoopGroup-5-1] io.netty.handler.logging.LoggingHandler  : [id: 0xae42d441, L:/172.31.208.1:58682 - R:/172.31.208.1:11996] FLUSH
2021-05-13 11:23:01.585 DEBUG 19604 --- [ntLoopGroup-3-2] io.netty.handler.logging.LoggingHandler  : [id: 0x824154a2, L:/172.31.208.1:11996 - R:/172.31.208.1:58682] READ: 153B
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| fd ac 01 01 00 00 00 00 00 00 00 00 02 00 00 00 |................|
|00000010| 88 ac ed 00 05 77 50 00 25 63 6f 6d 2e 67 69 74 |.....wP.%com.git|
|00000020| 68 75 62 2e 77 75 2e 73 70 72 69 6e 67 2e 62 69 |hub.wu.spring.bi|
|00000030| 7a 2e 45 6d 61 69 6c 53 65 72 76 69 63 65 00 04 |z.EmailService..|
|00000040| 65 63 68 6f 00 21 6a 61 76 61 2e 6c 61 6e 67 2e |echo.!java.lang.|
|00000050| 53 74 72 69 6e 67 2c 6a 61 76 61 2e 6c 61 6e 67 |String,java.lang|
|00000060| 2e 53 74 72 69 6e 67 75 72 00 02 5b 42 ac f3 17 |.Stringur..[B...|
|00000070| f8 06 08 54 e0 02 00 00 78 70 00 00 00 04 22 77 |...T....xp...."w|
|00000080| 75 22 75 71 00 7e 00 00 00 00 00 0d 22 68 65 6c |u"uq.~......"hel|
|00000090| 6c 6f 20 77 6f 72 6c 64 22                      |lo world"       |
+--------+-------------------------------------------------+----------------+
2021-05-13 11:23:01.586  WARN 19604 --- [ntLoopGroup-3-2] io.netty.channel.DefaultChannelPipeline  : An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

io.netty.handler.codec.DecoderException: com.github.wu.common.exception.UnsupportedProtocolException: magic: -21267
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:271) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: com.github.wu.common.exception.UnsupportedProtocolException: magic: -21267
	at com.github.wu.core.transport.SengMessageDecoder.decode(SengMessageDecoder.java:44) ~[classes/:na]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-all-4.1.52.Final.jar:4.1.52.Final]
	... 25 common frames omitted

```

**Comment by wangyongxu** [comment]
@Michelleqian
